import type { Metadata } from 'next';
export const dynamic='force-dynamic';
import './globals.css';
import {SiteIntro} from '@/components/site-intro';
import {loadSite,safeImage,defaults,initialItems,initialArticleSections,serviceDetailItems,approvedServiceItems} from '@/lib/site';
import {englishRecords} from '@/lib/english';
import {SiteLocalization} from '@/components/site-localization';
export async function generateMetadata():Promise<Metadata>{const {settings}=await loadSite();const logo=safeImage(settings.logo)||'/fast-zone-emblem-transparent.png';const favicon=logo==='/fast-zone-emblem-transparent.png'?logo+'?v=2':logo;return {title:{default:'فاست زون | صيانة السيارات',template:'%s | فاست زون'},description:'خدمات فحص وصيانة السيارات في المدينة المنورة',icons:{icon:[{url:favicon}],shortcut:favicon,apple:favicon}}}
export default async function RootLayout({children}:{children:React.ReactNode}){const {settings,items}=await loadSite();const custom:Record<string,string>={};for(const item of items){const old=[...approvedServiceItems,...initialItems,...initialArticleSections,...serviceDetailItems].find(x=>x.id===item.id);const base=englishRecords[item.id];let en:Record<string,string>={};try{en=JSON.parse(settings['translation:'+item.id]||'{}')}catch{}for(const key of ['title','body','price'] as const){const value=item[key];const translation=en[key]||(old?.[key]===value?base?.[key]:'');if(value&&translation){custom[value]=translation;const a=value.split("\n"),b=translation.split("\n");if(a.length===b.length)a.forEach((line,i)=>custom[line]=b[i])}}}for(const [key,value] of Object.entries(settings)){if(key.startsWith('englishSetting:')){const original=settings[key.slice(15)];if(original&&value)custom[original]=value}}return <html lang="ar" dir="rtl" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{__html:"try{const l=localStorage.getItem('fast-zone-language');const t=localStorage.getItem('fast-zone-theme');document.documentElement.dataset.theme=t==='light'?'light':'dark';if(l==='en'&&!location.pathname.startsWith('/admin')){document.documentElement.lang='en';document.documentElement.dir='ltr';document.documentElement.classList.add('localizing')}}catch(e){}"}}/><script dangerouslySetInnerHTML={{__html:"try{if(!location.pathname.startsWith('/admin')&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!(document.referrer.startsWith(location.origin)&&performance.getEntriesByType('navigation')[0]?.type!=='reload')){document.documentElement.classList.add('fz-intro-pending');setTimeout(()=>document.documentElement.classList.remove('fz-intro-pending'),5000)}}catch(e){}"}}/></head><body><SiteLocalization custom={custom}/><SiteIntro settings={settings}/>{children}</body></html>}
