'use client';
import {useEffect,useRef,useState} from 'react';
import type {Item} from '@/lib/site';
import {ArrowDown} from 'lucide-react';

function Paragraphs({text}:{text:string}){return <div className="story-copy">{text.split(/\n\s*\n|\n/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}</div>}
export function ArticleStory({intro,sections}:{intro:string,sections:Item[]}){
 const scope=useRef<HTMLDivElement>(null),[progress,setProgress]=useState(0),[active,setActive]=useState(0);
 useEffect(()=>{const root=scope.current;if(!root)return;root.classList.add('story-ready');const panels=[...root.querySelectorAll<HTMLElement>('[data-story-panel]')];const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('story-visible');const n=Number((entry.target as HTMLElement).dataset.storyPanel);setActive(n)}}},{rootMargin:'-12% 0px -25% 0px',threshold:0.12});panels.forEach(panel=>observer.observe(panel));const update=()=>{const box=root.getBoundingClientRect();const total=Math.max(1,root.offsetHeight-window.innerHeight);setProgress(Math.max(0,Math.min(100,Math.round(-box.top/total*100))))};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{observer.disconnect();window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);
 return <div className="story" ref={scope}><div className="story-progress" aria-hidden="true"><span style={{width:progress+'%'}}/></div><div className="story-rail" aria-hidden="true"><span>{String(Math.min(active+1,sections.length+1)).padStart(2,'0')} / {String(sections.length+1).padStart(2,'0')}</span><span>{progress}%</span></div><section className="story-opening" data-story-panel="0"><div className="story-opening-rule"/><span className="eyebrow">الفكرة الأساسية</span><Paragraphs text={intro}/>{sections.length>0&&<div className="story-scroll-cue"><ArrowDown size={20}/> تابع القراءة</div>}</section>{sections.map((part,index)=><section className={'story-chapter'+(part.image?' with-image':'')} key={part.id} data-story-panel={index+1} aria-labelledby={'chapter-'+part.id}><div className="story-chapter-text"><span className="story-chapter-number">{String(index+1).padStart(2,'0')}</span><span className="eyebrow">{String(index+1).padStart(2,'0')} — {String(sections.length).padStart(2,'0')}</span><h2 id={'chapter-'+part.id}>{part.title}</h2><Paragraphs text={part.body}/></div>{part.image&&<figure className="story-chapter-image"><img loading="lazy" src={part.image} alt={part.title}/></figure>}</section>)}</div>
}
