'use client';
import {useEffect,useState} from 'react';
import {ShoppingBag,Plus,Check,Trash2,MessageCircle,X} from 'lucide-react';

export type Choice={id:string;title:string;price:string;service:string};
const key='fast-zone-service-selection-v1';
function read():Choice[]{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string').slice(0,30):[]}catch{return []}}
function save(items:Choice[]){localStorage.setItem(key,JSON.stringify(items));window.dispatchEvent(new Event('fast-zone-cart-change'))}

export function AddToCart({choice}:{choice:Choice}){const [added,setAdded]=useState(false);useEffect(()=>{const sync=()=>setAdded(read().some(x=>x.id===choice.id));sync();window.addEventListener('fast-zone-cart-change',sync);return()=>window.removeEventListener('fast-zone-cart-change',sync)},[choice.id]);return <button type="button" className={'btn small '+(added?'ghost':'')} onClick={()=>{const items=read();save(added?items.filter(x=>x.id!==choice.id):[...items,choice]);window.dispatchEvent(new Event('fast-zone-cart-open'))}}>{added?<Check size={17}/>:<Plus size={17}/>} {added?'أُضيفت إلى خدماتي':'أضف إلى خدماتي'}</button>}

export function ServiceCart({whatsapp}:{whatsapp:string}){const [items,setItems]=useState<Choice[]>([]),[open,setOpen]=useState(false),[name,setName]=useState(''),[phone,setPhone]=useState(''),[car,setCar]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState('');useEffect(()=>{const sync=()=>setItems(read());const show=()=>setOpen(true);sync();window.addEventListener('fast-zone-cart-change',sync);window.addEventListener('fast-zone-cart-open',show);return()=>{window.removeEventListener('fast-zone-cart-change',sync);window.removeEventListener('fast-zone-cart-open',show)}},[]);
const number=whatsapp.replace(/\D/g,'');
function send(e:React.FormEvent){e.preventDefault();if(!items.length){setMessage('اختر خدمة واحدة على الأقل.');return}if(!/^\d{10,15}$/.test(number)){setMessage('رقم واتساب المركز غير مهيأ بعد.');return}const lines=['مرحبًا فاست زون، أود الاستفسار وحجز الخدمات التالية:',...items.map((x,i)=>`${i+1}. ${x.service}${x.service!==x.title?' — '+x.title:''}${x.price?' · '+x.price:''}`),'','الاسم: '+name.trim(),'الجوال: '+phone.trim(),'السيارة: '+car.trim(),...(notes.trim()?['ملاحظات: '+notes.trim()]:[]),'','أرجو التواصل معي لتأكيد التفاصيل والموعد.'];window.open(`https://wa.me/${number}?text=${encodeURIComponent(lines.join('\n'))}`,'_blank','noopener,noreferrer');setMessage('فُتحت رسالة واتساب. اضغط إرسال داخل واتساب لإتمام الطلب.');}
return <><button type="button" className="cart-float" onClick={()=>setOpen(true)} aria-label={`قائمة الخدمات المختارة: ${items.length}`}><ShoppingBag size={20}/> خدماتي <span>{items.length}</span></button>{open&&<div className="cart-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="cart-panel" role="dialog" aria-modal="true" aria-label="الخدمات المختارة"><header><div><span className="eyebrow">طلبك</span><h2>خدماتي المختارة</h2></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)} aria-label="إغلاق"><X/></button></header>{items.length?<><ul className="cart-items">{items.map(x=><li key={x.id}><div><strong>{x.service}{x.service!==x.title?' · '+x.title:''}</strong><small>{x.price||'السعر عند الاستفسار'}</small></div><button type="button" className="icon-btn" aria-label={'إزالة '+x.title} onClick={()=>save(items.filter(i=>i.id!==x.id))}><Trash2 size={17}/></button></li>)}</ul><form onSubmit={send} className="cart-form"><p className="muted">أكمل بياناتك، ثم راجع الرسالة وأرسلها بنفسك عبر واتساب. الموعد يُؤكد بعد رد المركز.</p><label className="label">الاسم<input className="field" value={name} required maxLength={100} onChange={e=>setName(e.target.value)}/></label><label className="label">رقم الجوال<input className="field" dir="ltr" type="tel" value={phone} required pattern="[0-9+() -]{8,20}" onChange={e=>setPhone(e.target.value)}/></label><label className="label">السيارة والموديل<input className="field" value={car} required maxLength={100} onChange={e=>setCar(e.target.value)}/></label><label className="label">ملاحظات (اختياري)<textarea className="field" value={notes} maxLength={500} onChange={e=>setNotes(e.target.value)}/></label><button className="btn" type="submit"><MessageCircle size={19}/> إرسال خدماتي عبر واتساب</button><a className="btn ghost" href="/services" style={{textAlign:"center"}}>إضافة مزيد من الخدمات</a><p role="status" aria-live="polite">{message}</p></form></>:<div className="empty">لم تختر أي خدمة بعد. <a href="/services" className="eyebrow">تصفح الخدمات</a></div>}</section></div>}</>}
