// This article is seeded once and then editable from the dashboard.
export const coolingArticle={
 id:'cooling-system-cleaning-guide',
 title:'متى تحتاج دورة تبريد سيارتك إلى التنظيف؟',
 englishTitle:'When does your car’s cooling system need cleaning?',
 intro:[
  ['سائل التبريد ينقل الحرارة بعيدًا عن المحرك، وتساعد إضافاته على حماية أجزاء الدورة من التآكل. ومع الاستخدام الطويل أو اختيار سائل غير مناسب، قد تتراجع هذه الحماية أو تظهر رواسب وتسربات.','Coolant carries heat away from the engine, while its additives help protect cooling-system components from corrosion. Over time, or with the wrong fluid, that protection can weaken and deposits or leaks may develop.'],
  ['لكن ارتفاع الحرارة لا يعني دائمًا أن الدورة تحتاج إلى غسيل. نبدأ بتحديد السبب: هل المشكلة في السائل، أم في تسرب، أو بلف حرارة، أو مروحة، أو جزء آخر؟','Overheating does not always mean the system needs flushing. Start by finding the cause: is it the coolant, a leak, a thermostat, a fan, or something else?'],
 ],
 sections:[
  {id:'cooling-signs',title:'إشارات تستحق الفحص قبل ارتفاع الحرارة',englishTitle:'Signs worth checking before the engine overheats',paragraphs:[
   ['تغيّر غير معتاد في لون السائل، أو ظهور شوائب ورواسب في القربة، يستدعي فحص العينة ومصدر التلوث. لون الصبغة وحده لا يحدد نوع السائل ولا يكفي للحكم على صلاحيته.','An unusual color change or visible debris in the reservoir calls for inspection of the fluid and the contamination source. Dye color alone cannot identify the coolant type or establish whether it remains serviceable.'],
   ['استمرار المراوح في العمل بسرعة عالية أو تذبذب مؤشر الحرارة بين الوقوف والسير قد يرتبطان بعطل في أكثر من جزء؛ لذلك تُراجع القراءات والمراوح والرديتر ومستوى السائل بدل افتراض وجود انسداد.','Fans running at high speed or a temperature gauge that changes between idling and driving can have several causes. Check the readings, fans, radiator, and coolant level before assuming a blockage.'],
   ['ضعف تدفئة المقصورة شتاءً قد يدل على انخفاض السائل أو وجود هواء أو تقييد في ثلاجة التدفئة (Heater Core). وهي جزء مختلف عن ثلاجة المكيف.','Weak cabin heating in winter can point to low coolant, trapped air, or a restriction in the heater core. The heater core is separate from the air-conditioning evaporator.'],
   ['إذا ارتفعت حرارة المحرك، توقف في مكان آمن واتبع تعليمات سيارتك. لا تفتح غطاء الرديتر أو القربة المضغوطة والمحرك ساخن.','If the engine overheats, stop somewhere safe and follow your vehicle’s instructions. Do not open a pressurized radiator or reservoir cap while the engine is hot.'],
  ]},
  {id:'cooling-diagnosis',title:'01 — افحص السائل والضغط قبل اختيار العلاج',englishTitle:'01 — Check the fluid and pressure before choosing a treatment',paragraphs:[
   ['تُراجع مواصفة السائل المستخدم وتركيزه وحالته. قد يساعد مقياس الانكسار في تقدير تركيز الحماية من التجمد، بينما تُستخدم اختبارات الحموضة والإضافات عندما تلائم نوع السائل وتعليمات فحصه؛ لا تكشف قراءة pH وحدها حالته كاملة.','Check the coolant specification, concentration, and condition. A refractometer can help estimate freeze protection; pH and inhibitor tests may be useful when appropriate for the coolant. A pH reading alone does not describe its full condition.'],
   ['بعد أن تبرد السيارة، يُختبر ضغط المنظومة وغطاؤها بالمعدات والقيمة التي تحددها الشركة المصنعة، مع البحث عن آثار التسرب عند الليات والوصلات ومضخة الماء والرديتر. يُصلح مصدر التسرب قبل تعبئة سائل جديد.','After the vehicle cools, the system and cap are pressure-tested using the equipment and pressure specified by the manufacturer. Hoses, connections, water pump, and radiator are checked for leaks. Fix the leak before adding new coolant.'],
  ]},
  {id:'cooling-flush',title:'02 — تنظيف المسارات: حسب نوع الرواسب وحالة القطع',englishTitle:'02 — Cleaning the passages: match the method to the problem',paragraphs:[
   ['إذا أكد الفحص وجود رواسب أو تلوث يستدعي الشطف، يُفرغ السائل القديم ويُختار إجراء تنظيف مناسب لمواد الرديتر والمحرك وتعليمات السيارة. ليست كل منظومة بحاجة إلى محلول كيميائي، ولا تصلح مادة واحدة لكل أنواع التلوث.','If inspection confirms deposits or contamination that warrant flushing, the old fluid is drained and a procedure compatible with the radiator, engine materials, and vehicle instructions is chosen. Not every system needs a chemical cleaner, and no single product fits every contaminant.'],
   ['قد يُستخدم الشطف العكسي لرديتر أو ثلاجة تدفئة مسدودة عندما تسمح تعليمات الصيانة بذلك، وبضغط وتدفق مناسبين للأجزاء الحساسة. لا يُفترض توصيل تدفق عكسي نابض إلى كامل دورة المحرك لكل سيارة.','A reverse flush may help a restricted radiator or heater core where service instructions allow it, using pressure and flow safe for those components. A pulsed reverse flow through an entire engine cooling system is not a universal procedure.'],
   ['بعد التنظيف تُزال بقايا المادة والشوائب بالطريقة المعتمدة قبل تعبئة السائل الجديد، مع جمع السائل المستعمل والتخلص منه على نحو مناسب.','After cleaning, any product residue and debris are removed using the approved method before refilling. Used coolant is collected and disposed of appropriately.'],
  ]},
  {id:'cooling-thermostat',title:'03 — بلف الحرارة والليات: افحص السبب المرتبط بهما',englishTitle:'03 — Thermostat and hoses: check the related cause',paragraphs:[
   ['يُنظَر إلى عمل بلف الحرارة (Thermostat) إذا دلت القراءات على تأخر وصول المحرك لحرارة التشغيل أو ارتفاعها بشكل غير طبيعي. تعليقه في وضع الفتح أو الإغلاق له أثر مختلف، وقد يحتاج البلف إلى استبدال بدل محاولة تنظيفه.','The thermostat is assessed when readings show slow warm-up or abnormal overheating. Sticking open and sticking closed have different effects; replacement may be more appropriate than attempting to clean a faulty thermostat.'],
   ['تُفحص الليات والوصلات بحثًا عن التشقق أو الليونة الزائدة أو الانثناء أو الانسداد، وتُراجع مضخة الماء ومروحة التبريد عند الحاجة. معالجة السبب تحمي المنظومة من تكرار المشكلة بعد تغيير السائل.','Hoses and connections are checked for cracks, excessive softness, kinks, or blockages; the water pump and cooling fan are checked where indicated. Fixing the cause helps prevent the issue from returning after a coolant change.'],
  ]},
  {id:'cooling-fill',title:'04 — تعبئة السائل وطرد الهواء: اتبع مواصفة السيارة',englishTitle:'04 — Refill and remove air: follow the vehicle specification',paragraphs:[
   ['يُستخدم سائل تبريد بالمواصفة المعتمدة لسيارتك، سواء كان جاهزًا للاستخدام أو مركزًا يُخلط بالنسبة ونوع الماء اللذين تحددهما الشركة. تسميات OAT وHOAT وحدها أو لون العبوة لا تكفي لاختيار السائل المناسب.','Use coolant approved for your vehicle, whether premixed or a concentrate diluted with the ratio and water type specified by the manufacturer. OAT or HOAT labels alone, or the bottle’s color, are not enough to select the correct fluid.'],
   ['يمكن أن تساعد أداة التعبئة بالتفريغ في بعض السيارات على تقليل الهواء المحبوس، بينما تعتمد سيارات أخرى خطوات تنفيس محددة. المهم اتباع إجراء الطرد الصحيح والتحقق من مستوى السائل بعد وصول المحرك إلى ظروف التشغيل الموصى بها ثم بعد أن يبرد.','A vacuum filling tool can help reduce trapped air on some vehicles; others have specific bleeding steps. Follow the correct procedure and check the coolant level under the recommended operating conditions and again after the engine cools.'],
  ]},
  {id:'cooling-takeaway',title:'الصيانة الجيدة تبدأ بتحديد السبب',englishTitle:'Good maintenance begins by finding the cause',paragraphs:[
   ['التعامل المبكر مع التلوث أو نقص السائل أو ضعف التدفق قد يقلل خطر ارتفاع حرارة المحرك وتلف مكونات الدورة. لكن الغسيل الدوري وحده لا يضمن حماية مضخة الماء أو رأس المحرك إذا استمر تسرب أو تعطل مروحة أو بلف حرارة.','Addressing contamination, low coolant, or poor flow early may reduce the risk of overheating and damage. Flushing alone cannot protect the water pump or cylinder head if a leak, fan fault, or thermostat problem remains.'],
   ['اطلب فحصًا يوضح حالة السائل، وسبب العَرَض، ومواصفة البديل قبل الموافقة على تنظيف الدورة أو تعبئتها. بهذه الخطوة تصبح الصيانة مناسبة لسيارتك لا مجرد إجراء متكرر.','Ask for a check that explains the fluid condition, the symptom’s cause, and the replacement specification before approving a flush or refill. That makes the service appropriate for your car rather than a routine applied to every vehicle.'],
  ]},
 ]
} as const;
