// Initial, editable content for the service pages. Poster details remain scoped to their service.
export const deepCleaningService={
 id:'deep-cleaning',title:'عرض خدمات التنظيف الشامل',englishTitle:'Comprehensive cleaning offer',
 body:'باقة لتنظيف أجزاء محددة من منظومة المحرك والعادم، تشمل التوربو ودبة البيئة وحساس الأكسجين والبخاخات وثلاجة المحرك وبوابة الهواء، مع فحص دبة البيئة بالكاميرا وبرمجة السيارة. تُحدد طريقة التنفيذ بعد فحص السيارة وملاءمة الأجزاء.',
 englishBody:'A cleaning package for selected engine and exhaust components: turbocharger, catalytic converter, oxygen sensor, injectors, engine intake manifold, and throttle body, plus camera inspection of the catalytic converter and vehicle programming. The service method depends on the vehicle and inspection.',
 image:'/deep-cleaning-machine.webp',category:'cat-engine',price:'تبدأ من 250 ريال',englishPrice:'From SAR 250',position:9,
} as const;

export const deepCleaningPackages=[
 {id:'deep-cleaning-four',title:'سيارات 4 سلندر',englishTitle:'4-cylinder vehicles',body:'تشمل أعمال التنظيف والفحص والبرمجة المذكورة في هذه الصفحة، وفق ملاءمة السيارة.',englishBody:'Includes the cleaning, inspection, and programming listed on this page, where suitable for the vehicle.',price:'250 ريال',englishPrice:'SAR 250',image:'/deep-cleaning-machine.webp'},
 {id:'deep-cleaning-six',title:'سيارات 6 سلندر ديزل',englishTitle:'6-cylinder diesel vehicles',body:'تشمل أعمال التنظيف والفحص والبرمجة المذكورة في هذه الصفحة، وفق ملاءمة السيارة.',englishBody:'Includes the cleaning, inspection, and programming listed on this page, where suitable for the vehicle.',price:'300 ريال',englishPrice:'SAR 300',image:'/deep-cleaning-turbo.webp'},
] as const;

type Feature={id:string;service:string;title:string;englishTitle:string;body:string;englishBody:string;image?:string};
export const serviceFeatures:Feature[]=[
 {id:'clean-turbo',service:'deep-cleaning',title:'تنظيف التوربو وإزالة الترسبات الصعبة',englishTitle:'Turbocharger cleaning',body:'تنظيف الجزء المناسب من منظومة التوربو والترسبات التي يمكن الوصول إليها، بحسب نوع السيارة وحالة التوربو.',englishBody:'Cleaning suitable parts of the turbo system and accessible deposits, according to vehicle type and condition.',image:'/deep-cleaning-turbo.webp'},
 {id:'clean-converter',service:'deep-cleaning',title:'تنظيف دبة البيئة',englishTitle:'Catalytic converter cleaning',body:'تنظيف دبة البيئة بوسيلة ملائمة لحالتها بعد الفحص، دون اعتبار التنظيف بديلًا عن إصلاح التلف الداخلي.',englishBody:'Clean the catalytic converter with a method suitable for its condition after inspection; cleaning cannot repair internal damage.',image:'/catalyst-editorial.webp'},
 {id:'clean-oxygen',service:'deep-cleaning',title:'تنظيف حساس الأكسجين',englishTitle:'Oxygen sensor cleaning',body:'فحص وتنظيف حساس الأكسجين عندما تكون حالته تسمح بذلك، مع التأكد من عمله بعد الخدمة.',englishBody:'Inspect and clean the oxygen sensor where its condition permits, then check its operation.',image:'/catalyst-sensors.webp'},
 {id:'clean-injectors',service:'deep-cleaning',title:'تنظيف البخاخات وتنظيم الرش',englishTitle:'Injector cleaning and spray check',body:'تنظيف البخاخات وفحص نمط الرش بحسب نوع نظام الحقن وتجهيزات السيارة.',englishBody:'Clean injectors and check the spray pattern according to the injection system and vehicle.',image:'/deep-cleaning-injectors.webp'},
 {id:'clean-manifold',service:'deep-cleaning',title:'تنظيف ثلاجة المحرك',englishTitle:'Intake manifold cleaning',body:'تنظيف رواسب مجرى السحب أو ثلاجة المحرك بالطريقة الملائمة لتصميمها وإمكانية الوصول إليها.',englishBody:'Clean deposits in the intake manifold using a method suited to its design and accessibility.',image:'/engine-tune-editorial.webp'},
 {id:'clean-throttle',service:'deep-cleaning',title:'تنظيف صمامات وبوابة الهواء',englishTitle:'Throttle body and air-valve cleaning',body:'تنظيف بوابة الهواء والأجزاء المناسبة حولها مع مراعاة حساسية الأجزاء الإلكترونية.',englishBody:'Clean the throttle body and suitable surrounding parts while protecting sensitive electronic components.',image:'/engine-tune-air.webp'},
 {id:'clean-camera',service:'deep-cleaning',title:'فحص دبة البيئة بالكاميرا',englishTitle:'Catalytic converter camera inspection',body:'معاينة حالة دبة البيئة بالكاميرا للمساعدة في تحديد مدى ملاءمة التنظيف.',englishBody:'Use a camera to inspect the converter and help determine whether cleaning is appropriate.',image:'/catalyst-temperature.webp'},
 {id:'clean-programming',service:'deep-cleaning',title:'برمجة السيارة',englishTitle:'Vehicle programming',body:'فحص إلكتروني وإجراء البرمجة أو التهيئة المناسبة بعد الخدمة إذا احتاجت السيارة لذلك.',englishBody:'Electronic checks and suitable programming or relearn procedures after service when the vehicle requires them.',image:'/deep-cleaning-diagnostics.webp'},
 {id:'clean-egr-extra',service:'deep-cleaning',title:'تنظيف EGR · خدمة إضافية برسوم',englishTitle:'EGR cleaning · extra charge',body:'تنظيف نظام تدوير غازات العادم متاح كخدمة إضافية؛ يُحدد سعره قبل التنفيذ.',englishBody:'Exhaust gas recirculation cleaning is available as a separately charged service; its price is confirmed before work.',image:'/deep-cleaning-egr.webp'},
 {id:'oil-change',service:'engine-oil',title:'تغيير الزيت والسيفون',englishTitle:'Oil and filter change',body:'تغيير الزيت وفلتره وفق مواصفات السيارة؛ أجور اليد المعلنة 20 ريال.',englishBody:'Change the engine oil and filter according to the vehicle specification; listed labor charge is SAR 20.',image:'/oil-care-filter.webp'},
 {id:'oil-tires',service:'engine-oil',title:'فحص الإطارات',englishTitle:'Tire inspection',body:'فحص حالة الإطارات ضمن الخدمة.',englishBody:'Check tire condition as part of the service.',image:'/preventive-care-suspension.webp'},
 {id:'oil-air',service:'engine-oil',title:'تنظيف فلتر الهواء والماكينة بالهواء',englishTitle:'Air filter and engine-bay air cleaning',body:'تنظيف فلتر الهواء والماكينة بالهواء كما هو مذكور ضمن الخدمة.',englishBody:'Air-clean the air filter and engine bay as listed for this service.',image:'/engine-tune-air.webp'},
 {id:'computer-scan',service:'computer',title:'فحص الأعطال بالكمبيوتر',englishTitle:'Computer fault scan',body:'قراءة الأكواد المسجلة في كمبيوتر السيارة.',englishBody:'Read fault codes stored in the vehicle computer.',image:'/deep-cleaning-diagnostics.webp'},
 {id:'computer-report',service:'computer',title:'إرسال تقرير الفحص',englishTitle:'Send the inspection report',body:'إرسال نتيجة الفحص للعميل عبر واتساب.',englishBody:'Send the inspection findings to the customer by WhatsApp.'},
 {id:'computer-clear',service:'computer',title:'مسح الأكواد',englishTitle:'Clear diagnostic codes',body:'مسح الأكواد عند ملاءمة ذلك بعد حفظ نتيجة الفحص.',englishBody:'Clear codes where appropriate after recording the findings.'},
 {id:'radiator-external',service:'radiator',title:'باقات تنظيف الليات الخارجية',englishTitle:'External cooling hose packages',body:'تتوفر باقة أساسية وشاملة بحسب نطاق الخدمة المبين في الأسعار أدناه.',englishBody:'Basic and comprehensive packages are available as detailed below.',image:'/package-cooling.webp'},
 {id:'radiator-internal',service:'radiator',title:'الليات الداخلية والهايبرد والسيارات الكبيرة',englishTitle:'Internal hoses, hybrids, and large vehicles',body:'تتوفر باقات مخصصة لهذه الفئة؛ جميع الباقات لا تشمل سائل التبريد.',englishBody:'Dedicated packages are available; coolant is not included in any package.',image:'/cooling-flush.webp'},
 {id:'steering-fluid',service:'steering',title:'خدمة تغيير زيت الدركسون',englishTitle:'Power-steering fluid change',body:'تغيير سائل التوجيه للمركبات التي تستخدم هذه المنظومة؛ الزيت غير مشمول ويُوفّره العميل.',englishBody:'Replace steering fluid on vehicles fitted with this system; the fluid is not included and is supplied by the customer.'},
 {id:'catalytic-inspection',service:'catalytic',title:'فحص دبة البيئة وتنظيف الحساس',englishTitle:'Converter and oxygen sensor check',body:'فحص دبة البيئة الواحدة وتنظيف حساس الأكسجين بحسب باقة الفحص.',englishBody:'Inspect one catalytic converter and clean its oxygen sensor under the inspection package.',image:'/catalyst-sensors.webp'},
 {id:'catalytic-cleaning',service:'catalytic',title:'التبخير أو الرغوة',englishTitle:'Vapor or foam cleaning',body:'تتوفر باقات منفصلة للتبخير والرغوة؛ راجع تفاصيل كل باقة وسعرها أدناه.',englishBody:'Separate vapor and foam options are available; see each package and its price below.',image:'/package-exhaust.webp'},
 {id:'tune-inspection',service:'engine-tune',title:'فحص أداء الماكينة',englishTitle:'Engine performance check',body:'تحديد أعمال الفحص والتنظيف المناسبة حسب حالة السيارة والباقة المختارة.',englishBody:'Determine suitable inspection and cleaning work based on vehicle condition and the selected package.',image:'/engine-tune-editorial.webp'},
 {id:'head-check',service:'engine-head',title:'فحص رأس الماكينة',englishTitle:'Cylinder head inspection',body:'تقييم حالة رأس الماكينة باستخدام أجهزة فحص متخصصة.',englishBody:'Assess the cylinder head with specialized diagnostic equipment.'},
 {id:'smoke-check',service:'smoke',title:'كشف التهريب بالدخان',englishTitle:'Smoke leak detection',body:'استخدام جهاز الدخان لتحديد مواقع التسرب في الأجزاء الملائمة للفحص.',englishBody:'Use a smoke machine to locate leaks in systems suitable for this test.'},
 {id:'battery-check',service:'battery',title:'فحص البطارية والدينمو والسلف',englishTitle:'Battery, alternator, and starter tests',body:'فحص كهرباء التشغيل والشحن بأجهزة متخصصة.',englishBody:'Test the starting and charging system with dedicated equipment.'},
];
