// Editorial content is seeded once; the dashboard remains its source of truth afterward.
export const transmissionArticle={
 id:'automatic-transmission-fluid-guide',
 title:'زيت القير الأوتوماتيكي: متى تغيّره وكيف تتم الصيانة الصحيحة؟',
 englishTitle:'Automatic transmission fluid: when and how should it be serviced?',
 intro:[
  ['زيت القير الأوتوماتيكي (ATF) ليس مجرد مادة تزييت؛ ففي نواقل الحركة التقليدية ينقل الضغط الهيدروليكي، ويساعد على التبريد، وتؤثر خصائص احتكاكه في طريقة تعشيق الكلتشات.','Automatic transmission fluid (ATF) does more than lubricate. In conventional automatics, it carries hydraulic pressure, helps cool the transmission, and its friction properties affect clutch engagement.'],
  ['لكن ليس كل ناقل حركة يستخدم الزيت نفسه أو يتبع طريقة الصيانة نفسها. قبل اختيار الاستبدال الجزئي أو الإجراء الأشمل، تبدأ القصة بتحديد نوع القير وحالته ومواصفات الشركة المصنعة.','Not every transmission uses the same fluid or follows the same service procedure. Before choosing a drain-and-fill or a more extensive exchange, identify the gearbox type, its condition, and the manufacturer’s instructions.'],
 ],
 sections:[
  {id:'atf-warning-signs',title:'متى يستحق القير فحصًا قبل موعد الصيانة؟',englishTitle:'When should you check the transmission before its next service?',paragraphs:[
   ['تأخر التعشيق عند الانتقال من P إلى D أو R، أو نتعة غير معتادة عند تبديل السرعات، إشارات تستحق فحص مستوى الزيت وحالة ناقل الحركة.','Delayed engagement when shifting from P into D or R, or an unusual jolt during gear changes, calls for a check of the fluid level and the transmission’s condition.'],
   ['إذا ارتفعت دورات المحرك (RPM) دون تسارع مماثل للسيارة، فقد يكون هناك انزلاق يحتاج إلى تشخيص سريع؛ تغيير الزيت وحده لا يعالج بالضرورة الكلتشات المتضررة.','If engine speed (RPM) rises without matching acceleration, the transmission may be slipping and needs prompt diagnosis. Changing fluid alone will not necessarily repair damaged clutches.'],
   ['تغيّر لون الزيت أو ظهور رائحة احتراق قد يبرران فحصًا أقرب، لكن لون الزيت وحده لا يكشف مقدار تآكله ولا يحدد سبب العطل. يُراجع أيضًا جدول الصيانة وتسرب الزيت واستخدام السيارة.','Darkened fluid or a burnt smell may warrant an earlier inspection, but color alone cannot measure wear or identify a fault. The maintenance schedule, leaks, and driving conditions also matter.'],
  ]},
  {id:'atf-diagnosis',title:'01 — التشخيص أولًا: ما الذي تقوله القراءات؟',englishTitle:'01 — Diagnose first: what do the readings show?',paragraphs:[
   ['تبدأ الخدمة بقراءة أكواد وحدة التحكم في ناقل الحركة وبيانات الحرارة والانزلاق والتعشيق عند توفرها، ثم فحص مستوى الزيت والتسربات. قد يرتبط العَرَض بمشكلة كهربائية أو هيدروليكية أو ميكانيكية لا تُحل باستبدال السائل.','Service starts by reading available transmission-control codes and data for temperature, slip, and engagement, then checking fluid level and leaks. The symptom may reflect an electrical, hydraulic, or mechanical problem that fluid replacement cannot solve.'],
   ['تُفحص عينة الزيت ورائحته وما يظهر في وعاء القير من رواسب. وقد تستدعي برادة معدنية كبيرة أو آثار احتكاك غير طبيعية اختبارًا أعمق؛ لا يمكن تحديد نسبة تلف الكلتشات بدقة من النظر إلى العينة وحدها.','The fluid sample, odor, and deposits in the pan are inspected. Significant metal debris or abnormal friction material may call for deeper testing; looking at a sample alone cannot quantify clutch wear precisely.'],
  ]},
  {id:'atf-exchange',title:'02 — استبدال الزيت: الطريقة تتبع نوع القير',englishTitle:'02 — Fluid exchange: the method follows the gearbox',paragraphs:[
   ['عند التفريغ من الصرة أو وعاء الزيت، يخرج جزء من إجمالي السائل، وتختلف النسبة بحسب تصميم الناقل. قد يبقى سائل في محول العزم والمبرد والمسارات الداخلية، لذلك تحدد تعليمات المصنع طريقة الخدمة والكمية المطلوبة.','Draining through the plug or pan removes part of the total fluid; the proportion depends on the transmission design. Fluid may remain in the torque converter, cooler, and internal passages, so manufacturer instructions determine the method and quantity.'],
   ['قد تسمح بعض النواقل بتبديل السائل عبر جهاز مناسب لمسار التبريد، بينما تفضّل نواقل أخرى التفريغ وإعادة التعبئة وفق إجراء محدد. لا يُفترض أن الجهاز يزيل 100% من الزيت، ولا يُستخدم ضغط زائد أو مادة غسيل من دون موافقة الشركة المصنعة.','Some transmissions permit a controlled exchange through a suitable cooling-line device; others call for a specified drain-and-fill procedure. No device should be assumed to remove 100% of the old fluid, and extra pressure or flushing chemicals must not be used without manufacturer approval.'],
   ['الأهم استخدام مواصفة الزيت الصحيحة للقير نفسه؛ فزيوت ATF وCVT وناقل الحركة مزدوج القابض ليست بدائل تلقائية لبعضها.','Most important is using fluid with the correct specification for that gearbox. ATF, CVT fluid, and dual-clutch transmission fluid are not automatically interchangeable.'],
  ]},
  {id:'atf-filter',title:'03 — الكارتير والفلتر: التفاصيل التي لا تُرى',englishTitle:'03 — Pan and filter: the details you cannot see',paragraphs:[
   ['إذا كان تصميم القير يسمح بفك الكارتير وخدمة الفلتر، تُفحص المغناطيسات والرواسب ويُنظَّف الوعاء، ثم يُستبدل الفلتر أو وحدة الفلتر المدمجة وحشيات الإحكام وفق تعليمات القطعة.','If the transmission design permits pan removal and filter service, the magnets and deposits are inspected and the pan cleaned. The filter or integrated filter unit and seals are replaced as specified for that gearbox.'],
   ['تُركّب المسامير بالتسلسل وعزم الشد الموصى بهما لتقليل مخاطر التسرب أو تلف القلاوظ. بعض النواقل لا يتطلب فك الكارتير في كل عملية تغيير، لذلك لا تُعمَّم هذه الخطوة على الجميع.','Fasteners are installed in the specified sequence and to the specified torque to reduce leaks or thread damage. Some transmissions do not require pan removal at every fluid change, so this is not a universal step.'],
  ]},
  {id:'atf-level',title:'04 — مستوى الزيت: الحرارة جزء من القياس',englishTitle:'04 — Fluid level: temperature is part of the measurement',paragraphs:[
   ['يختلف أسلوب قياس المستوى بين قير له عصا قياس، وآخر يستخدم فتحة تعبئة أو فائضًا مع إجراء محدد للتعشيق وتشغيل المحرك. القراءة الصحيحة تتطلب وضعية السيارة وحرارة الزيت المنصوص عليهما لنوع الناقل.','Level checks differ between transmissions with a dipstick and those using a fill or overflow port with a specified engine and gear-selection procedure. Correct readings require the vehicle position and fluid temperature specified for that transmission.'],
   ['لا توجد نافذة 35–50 درجة مئوية تصلح لجميع السيارات؛ حتى نواقل الشركات المختلفة قد تتطلب درجات أعلى أو أقل. يُرصد نطاق الحرارة المناسب بجهاز الفحص أو بالطريقة المعتمدة، لأن نقص الزيت أو زيادته قد يسببان مشكلات تشغيلية.','There is no universal 35–50°C window: different gearboxes may require higher or lower temperatures. The correct range is monitored with a scan tool or the approved method, since both underfilling and overfilling can cause operating problems.'],
   ['بعد الخدمة تُفحص التسربات ويُختبر التبديل. إعادة تعلّم أو تصفير قيم ناقل الحركة تُنفذ فقط إذا نصت تعليمات الشركة على ذلك أو استدعتها عملية الإصلاح، لا تلقائيًا عند كل تغيير زيت.','After service, leaks and shift behavior are checked. Transmission adaptation or learned-value resets are performed only when required by the manufacturer or a specific repair, not automatically with every oil change.'],
  ]},
  {id:'atf-takeaway',title:'الهدف: صيانة مناسبة، لا إجراء واحد للجميع',englishTitle:'The goal: the right service, not a universal procedure',paragraphs:[
   ['الصيانة الجيدة تجمع بين تشخيص حالة القير، واختيار الزيت المعتمد، وتطبيق طريقة التغيير ومستوى التعبئة المناسبين. إذا ظهرت نتعة أو انزلاق مستمران، فالأولوية لتحديد السبب قبل الوعد بأن الزيت الجديد سيحل المشكلة.','Good service combines diagnosis, the approved fluid, the correct exchange method, and accurate fill level. If jolts or slipping persist, identifying the cause comes before promising that new fluid will fix the problem.'],
   ['اتباع جدول الصيانة وإرشادات الناقل قد يساعد على الحفاظ على سلاسة التبديل وتقليل احتمالات التلف، لكن عمر القير ونتيجة الإصلاح يتأثران بحالته الفعلية وطريقة استخدامه.','Following the service schedule and gearbox instructions can help maintain smooth shifting and reduce the risk of damage, but transmission life and repair results depend on its actual condition and use.'],
  ]},
 ]
} as const;
